<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>022fe31d-dcc0-4014-83fc-584f34a7712b</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Keycloak.Authentication" Version="13.4.6-preview.1.26319.6" />
    <PackageReference Include="AWSSDK.S3" Version="4.0.101.4" />
    <PackageReference Include="Microsoft.AspNetCore.JsonPatch" Version="10.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.10" />
    <PackageReference Include="Microsoft.OpenApi" Version="2.11.0" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.16.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BiegusowoApi.Data\BiegusowoApi.Data.csproj" />
    <ProjectReference Include="..\BiegusowoApi.ServiceDefaults\BiegusowoApi.ServiceDefaults.csproj" />
  </ItemGroup>

<ItemGroup>
	<InternalsVisibleTo Include="Biegusowo.Tests" />
</ItemGroup>

<ItemGroup>
  <Folder Include="Auth\" />
</ItemGroup>


</Project>
